services:
  postgres-test:
    image: postgres:17
    container_name: postgres_test_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shikposh_test
      PGDATA: /data/postgres
    volumes:
      - postgres_test:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - test_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test:

networks:
  test_network:
    driver: bridge
